//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBodegaPineda.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int idCompra { get; set; }
        public int idProductos { get; set; }
        public int idProveedores { get; set; }
        public int idRegistroPeso { get; set; }
    }
}
