//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBodegaPineda.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedore()
        {
            this.RegistroPesoes = new HashSet<RegistroPeso>();
        }
    
        public int idProveedor { get; set; }
        public string nombreProveedor { get; set; }
        public string apellidoProveedor { get; set; }
        public string telefono { get; set; }
        public string domicilio { get; set; }
        public Nullable<int> rtn { get; set; }
        public string claveIhcafe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroPeso> RegistroPesoes { get; set; }
    }
}
